#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get install -y nginx

# Create a basic "Hello World!" index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx redirection for /redirect_me
sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me { return 301 https://www.blog.litunya.com; }' /etc/nginx/sites-enabled/default

# Test Nginx configuration and restart Nginx if successful
sudo nginx -t && sudo systemctl restart nginx
